### ISSUE TITLE
Not able to run ./bin/start_db correctly

### ISSUE THREAD

**Issue by liperrino** [xii1/movie-recommender-system#4]
I am getting errors when running it.

**Comment by liperrino** [comment]
Its is ok now.

**Comment by liperrino** [comment]
Please, I would like to know how you have proceeded to build this project? I am interested in recommendations system and I would like to build something like this from training to deployment. Thanks in advance

**Comment by xii1** [comment]
What's the errors?
Please make sure prerequisites and do as README sequentially for development.
