### ISSUE TITLE
Not Able to deploy it

### ISSUE THREAD

**Issue by liperrino** [xii1/movie-recommender-system#5]
Please can you help me.
This is what i obtained when i want to deploy it.
bash ./bin/deploy_prod 1 1
[+] Running 0/2
 ⠿ load-balancer Error                                                                                    0.8s
 ⠿ ai-service Error                                                                                       0.8s
Error response from daemon: manifest unknown

**Comment by xii1** [comment]
You should be run with tag 2.0.0 (this is the latest version).
https://github.com/xii1/movie-recommender-system/pkgs/container/movie-recommender
